supported_categories:
  - BASE-COND_BR
  #- BASE-NOP
  - BASE-BITBYTE
  - BASE-CMOV
  #- BASE-CONVERT
  #- BASE-DATAXFER
  - BASE-FLAGOP
  #- BASE-SETCC
  - BASE-LOGICAL
  
contract_observation_clause: arch # ct/arch
contract_execution_clause: #seq/cond/cond-bpas/bpas
  - seq

enable_ssbp_patch: true
enable_assist_page: false
feedback_driven_generator: true

input_main_region_size: 32768
enable_assist_page: true

# DEBUG: Need priming if using checkpoints, else will find violations simply due to differing init uarch state!
gem5_enable_cross_test_case_checkpoints: false

# Use 0 for random seed
test_case_generator_seed: 0
input_gen_seed: 0

avg_mem_accesses: 16
min_bb_per_function: 5
max_bb_per_function: 5
test_case_size: 16
input_gen_entropy_bits: 16
memory_access_zeroed_bits: 0

inputs_per_class: 2 # or larger

executor: 'x86-gem5'
gem5_location: "/code/gem5-docker"
gem5_checkpoint: "/code/gem5-docker/checkpoint"
gem5_output_location: "/code/gem5-docker/m5out"
gem5_binary: "/code/gem5-docker/build/X86/gem5.opt"
gem5_se: "/code/gem5-docker/configs/example/se.py"
gem5_orchestration: "simple"
gem5_flags:
  - "--cpu-type=DerivO3CPU" # DEBUG: Try TimingSimpleCPU
  - "--l1d_size=8kB"
  - "--l1i_size=8kB"
  - "--l2cache"
  # - "--ruby" # Only ever either --ruby OR (--caches && --l1traces)
  # - "--caches"
  # - "--l1traces"
  

gem5_test_case_path: "test_case"
gem5_trace_mode:  "data_cache"
gem5_batch_size:  1
gem5_restore:  0 # DEBUG: Need priming if using checkpoints

gem5_attacker_modes:
   atk1 :
       type: "final_cache" # Timing: "memory_trace"; State: "final_cache"
       sources : ["data_cache","instr_cache"] # ["data_cache","instr_cache"]
       order : "rp"

no_priming: true
gem5_ipc_parallelism: 1 # number of simultaneous gem5 processes to have running

logging_modes:
  - info
  - fuzzer_debug
  # - fuzzer_trace # Get unicorn traces
  # - coverage_debug